name: flutter_apply_hooked
description: flutter_hooks & single_bloc_base & signal_wave helpers for flutter_apply
version: 0.1.0
homepage: https://www.modulovalue.com
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>=2.4.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_apply:
    git:
      url: git@github.com:modulovalue/flutter_apply.git
  flutter_hooks: ^0.6.1
  signal_wave:
    git:
      url: git@github.com:modulovalue/signal_wave.git
  single_bloc_base: ^1.0.0

dev_dependencies:
  extra_pedantic: ^1.1.1+3
  test: ^1.5.0
  mockito: ^4.0.0